name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ubuntu-latest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Used to host cibuildwheel
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6'
          bundler-cache: true

      - name: Setup Ruby
        run: |
            gem install colorize
            gem install zip
            ruby setup.rb

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.18.0

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
            CIBW_BUILD: cp311-*
            CIBW_ARCHS: native
            CIBW_BEFORE_ALL_LINUX: >
                yum install -y ruby-2.6 &&
                gem install colorize &&
                gem install zip &&
                rake clean &&
                rake

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-ubuntu-latest
          path: ./wheelhouse/*.whl